### ISSUE TITLE
Need for a more international approach

### ISSUE THREAD

**Issue by johadalin** [johadalin/ram-pup#3]
Currently the selection of oz facts is way too small. We need more to appeal to a wider audience. 
Assigning to our top specialist in the area to get this sorted.

@br1-msw , grab a very beer and get on this

**Comment by br1-msw** [comment]
significant refactor now in branch

**Comment by johadalin** [comment]
Don't know if this ever will count as 'fixed', but closing for now for a sense of accomplishment
go team! 🚢
